#!/usr/bin/expect -f
set timeout 600

spawn ssh -o StrictHostKeyChecking=no root@192.168.200.121 "cd /root/ai_server && ./venv/bin/pip install -r requirements.txt"
expect {
    "*assword:*" {
        send "ColetteRae!2\r"
        exp_continue
    }
    timeout {
        puts "\nTimeout waiting for installation to finish."
        exit 1
    }
    eof {
        puts "\nInstallation process completed."
    }
}
